/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package task_visitor

fun main() {
    val tree = Tree(readln())
    println("Before visiting: $tree")
    tree.accept(Visitor())
    println("After visiting: $tree")
}
